Remove "npm bin" call because it is slow
benjie/local-npm-bin.vim pull request #1
Opened 2017-04-27 22:54 UTC by ohjames

2017-04-28 11:05 UTC, benjie requested changes
Excellent idea, well executed. One minor nit: please can you change the /usr/bin fallback to use "npm bin" since it's not always /usr/bin (e.g. /usr/local/bin or an NVM directory or otherwise non-standard path) 🙏

2017-04-28 11:10 UTC, ohjames commented
Good point!

2017-04-28 11:13 UTC, ohjames commented
Pushed over the top of the previous commit now, thanks for your help!

2017-04-28 13:01 UTC, benjie commented
Sorry, I should have spotted this earlier (but I was reviewing on my phone...) the functionality of this PR is more limited - previously it would fall back if you didn't have a locally installed version (e.g. if you have a `node_modules` folder but don't have `eslint` installed it'd still fall back to global) whereas now it will fail if you have node_modules but no local eslint even if you have global eslint. I'm thinking you should change it to something more like:

```viml
runtime plugin/neomake-local-eslint.vim
let s:stylelint_path = GetNpmPath('stylelint')
```

I don't imagine that'll be much refactoring? I'm no expert on VimL though...

2017-05-04 23:28 UTC, ohjames commented
@benjie should work now!

2017-05-04 23:28 UTC, ohjames commented on plugin/neomake-local-eslint.vim
> +    let binpath = system('echo -n $(npm bin)') . '/' . a:binname
`echo -n $(...)` used to avoid newline at end, vim doesn't seem to have a `strip`/`chomp` function.

2017-05-04 23:30 UTC, ohjames commented
Oh it doesn't work, vimscript is so turdy lol.

2017-05-04 23:39 UTC, ohjames commented
Okay now I've tested it properly.

2017-05-05 08:59 UTC, benjie approved these changes

2017-05-05 08:59 UTC, benjie commented
LGTM; will look at testing/merging later 👍

2017-05-06 13:30 UTC, ohjames commented
Cool, after that I wanted to add `tslint` (since `stylelint` is also supported and to avoid having to duplicate this `GetNpmBin` across plugins). Would that be cool? I like to use both TypeScript and JavaScript :)

2017-05-06 13:31 UTC, ohjames commented
Alternatively, if you don't want to add `tslint` I could move `GetNpmBin` into a plugin, and then have this plugin depend on that one?

2017-05-08 08:54 UTC, benjie commented
I'm totally cool with that; any npm module that's widely used in fact. Can rename it

2017-05-09 07:38 UTC, benjie approved these changes

2017-05-09 07:38 UTC, merged

2017-05-09 07:52 UTC, benjie commented
Thanks, I've merged this and then did a little tidying up on master that should make it slightly more efficient.